version: '3'
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - my_network
networks:
  my_network:
    driver: bridge